resources:
  repositories:
    - repository: topaz-conan-dev
      type: github
      endpoint: TopazLabs
      name: TopazLabs/topaz-conan-dev
      ref: master

jobs:
- job: Win2019
  workspace:
    clean: all
  pool:
    vmImage: 'windows-2019'
  steps:
    - template: win.yml